#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <sys/types.h>
#include <unistd.h>
#include <syslog.h>
 #include <sys/stat.h>

//Returns 0 if arguments are correct otherwise returns 1
//number-number of arguments in main function
//argv - table with Strings- arguments from main function
// note that argv[0] is program name
//TODO-not finished
int readArguments(int number,char **argv,char *source,char * goal)
{
     //copying paths using char *strcpy (char* strTo, const char* strFrom); 
    strcpy(source,argv[1]);
    strcpy(goal,argv[2]);

    return 0;
}

int main(int argc, char ** argv)
{
     //char tables for paths
    char source [200],goal [200];
    
    //checking and reading arguments
    if(readArguments(argc,argv,source,goal)==1)
    exit(-1);

    //forking the parent process
    pid_t pid;
     /* Fork off the parent process */       
        pid = fork();
        //if failure
        if (pid > 0) 
        {
                exit(-1);
        }
        // if it is native process
        else if(pid <0)
        {
            return 0;
        }
        //if pid==0 then it is childs process
        else
        {
         //now we have to umask in order to write to any files(for exmaple logs)
         //By setting the umask to 0, we will have full access to the files generated by the daemon
         umask(0);
         openlog("logFile",LOG_PID,LOG_DAEMON);
         syslog(LOG_INFO,"Deamon has just started\n");
         //about sitsid : https://linux.die.net/man/2/setsid
         pid_t sid=setsid();
         if (sid<0)
        {
 			syslog(LOG_ERR, "Error with session opening\n");
 			exit(-1);
 		}




        }
       
       


    

    
    


    //at the end of program we need to close log using
    closelog();



    return 0;
}

/**
 * 392. if(argumenty(argc,argv,zrodlowa,docelowa)==-1)
 * Argumenty podaje zgodnie z nastepujacym schematem :
 * /demon <sc_zr> <sc_doc> <-R> <-T czas_snu> <-M rozmiar_pliku>
sc_zr
sc_doc
-R
-T
-M
- Ścieżka źródłowa do synchronizacji
- Ścieżka docelowa
- Rekurencyjna synchronizacja folderów
- Czas w sekundach czuwania demona
- Próg rozmiaru pliku dla kopiowania <read/write | mmap/write>
 * 
 * 
 * 
 * 
 *
 *  */